#!/usr/bin/bash

a=$(lscpu | grep -w "Thread(s) per core:" | cut -c20-)
b=$(lscpu | grep -w "Core(s) per socket:" | cut -c20-)

echo
echo "---- General ----"
echo -e 'Distro\t| ' $(grep -w 'PRETTY_NAME=' /etc/os-release | cut -c13- | tr -d '""' )
echo -e 'Kernal\t| ' $(uname -rs)
echo -e 'Uptime\t| ' $(uptime -p | cut -c3-)
echo -ne 'Mobo\t| ' $(cat /sys/devices/virtual/dmi/id/board_{vendor,name,version})
echo
echo -e "\n---- CPU ----"
echo -e 'Model\t| ' $(lscpu | grep -w "Model name:" | cut -c12-)
echo -e 'Speed\t| ' $(lscpu | grep -w "CPU max MHz" | cut -c13-)
echo -e 'Cores\t| ' $b
echo -e 'Threads\t| ' "$(($a*$b))" 
echo
echo "---- GPU ----"
echo -e 'GPU\t| ' $(lspci -m | grep 'VGA' | cut -d '"' -f6)
echo
echo "---- RAM ----"
echo -e 'Memory\t| ' $(free -h | grep "Mem:" | cut -c5- | tr -s [:blank:] | tr ' ' ':'  | cut -d ':' -f2)"B"
echo -e 'Used\t| ' $(free -h | grep "Mem:" | cut -c5- | tr -s [:blank:] | tr ' ' ':'  | cut -d ':' -f3)"B"
echo -e 'Free\t| ' $(free -h | grep "Mem:" | cut -c5- | tr -s [:blank:] | tr ' ' ':'  | cut -d ':' -f4)"B"
echo
echo "---- Swap ----"
echo -e 'Swap\t| ' $(free -h | grep "Swap:" | cut -c6- | tr -s [:blank:] | tr ' ' ':'  | cut -d ':' -f2)"B"
echo -e 'Free\t| ' $(free -h | grep "Swap:" | cut -c6- | tr -s [:blank:] | tr ' ' ':'  | cut -d ':' -f4)"B"
echo
